basic/urls.py
from django.conf.urls import url
from django.urls import path
from basic import views

app_name = 'basic'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register/', views.UserFormView.as_view(), name='register'),
    url(r'^login/', views.LoginView.as_view(), name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^privacy-polite/', views.privacy, name="privacy"),
    url(r'^profile/(?P<page_num>\d+)/$', views.profile, name='profile'),
]

news/urls.py
from django.conf.urls import url
from django.urls import path
from news import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.show_news, name="index"),
    url(r'^api/', views.News.as_view()),
]

proj_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

# router = DefaultRouter()
# router.register(r'member', basic_view.MemberViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^oauth/', include('rest_framework_social_oauth2.urls'), name='social'),
    # apps
    url(r'^', include('basic.urls', namespace='basic')),
    url(r'^youtube/', include('youtube.urls', namespace='youtube')),
    url(r'^weather/', include('weather.urls', namespace='weather')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^recommend/', include('recommend.urls', namespace='recommend')),
]


if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basic/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class UserProfile(models.Model):
    nickname = models.CharField(blank=True, null=True, max_length=15, default=None)
    user_img = models.FileField(upload_to='user_img', blank=True, null=True)
    belong_to = models.OneToOneField(to=User, related_name='profile', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.belong_to.username)
    

class AppInfo(models.Model):
    appname = models.CharField(null=False, max_length=20)
    content = models.TextField()
    
    def __str__(self):
        return str(self.appname)
    

class Comment(models.Model):
    avatar = models.ForeignKey(null=True, blank=True, to=UserProfile, 
                               related_name='comment_avatar', on_delete=models.CASCADE)
    name = models.ForeignKey(null=True, to=User, related_name='comment_name', on_delete=models.CASCADE)
    comment = models.TextField(null=False, blank=False)
    submit_time = models.DateTimeField(default=timezone.now)
    belong_to = models.ForeignKey(null=True, blank=True, to=AppInfo, 
                                  related_name='under_comment', on_delete=models.CASCADE)

    def __str__(self):
        return self.comment.encode('utf-8')

basic/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nickname', 'user_img']

basic/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.contrib.auth.forms import AuthenticationForm
from social_core.backends.oauth import BaseOAuth2
from urllib.parse import urlencode
from .models import UserProfile
from .forms import UserForm
from .forms import ProfileForm


class UserFormView(View):
    form_class = UserForm
    template_name = 'basic/register.html'

    def get(self, request):
        form = self.form_class(None)
        source = request.get_full_path().strip('/').capitalize()
        return render(request, self.template_name, locals())

    def post(self, request):
        form = self.form_class(request.POST)
        source = request.get_full_path().strip('/').capitalize()

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(to='basic:index')
        return render(request, self.template_name, locals())


class LoginView(View):
    form_class = AuthenticationForm
    template_name = 'basic/register.html'

    def get(self, request):
        form = self.form_class(None)
        source = request.get_full_path().strip('/').capitalize()
        return render(request, self.template_name, locals())

    def post(self, request):
        form = self.form_class(request, data=request.POST)
        source = request.get_full_path().strip('/').capitalize()

        if form.is_valid():
            login(request, form.get_user())
            return redirect(to='basic:index')
        return render(request, self.template_name, locals())


def logout_view(request):
    logout(request)
    return redirect(to='basic:index')


def privacy(request):
    return render(request, "basic/PrivacyPolite.html", locals())


class FacebookOAuth2(BaseOAuth2):
    """GitHub OAuth authentication backend"""
    name = 'facebook'
    AUTHORIZATION_URL = 'https://facebook.com/login/oauth/authorize'
    ACCESS_TOKEN_URL = 'https://facebook.com/login/oauth/access_token'
    SCOPE_SEPARATOR = ','
    EXTRA_DATA = [
        ('id', 'id'),
        ('expires', 'expires')
    ]

    def get_user_details(self, response):
        """Return user details from GitHub account"""
        return {'username': response.get('login'),
                'email': response.get('email') or '',
                'first_name': response.get('name')}

    def user_data(self, access_token, *args, **kwargs):
        """Loads user data from service"""
        url = 'https://api.facebook.com/user?' + urlencode({
            'access_token': access_token
        })
        return self.get_json(url)


def index(request):
    return render(request, "basic/index.html", locals())


def profile(request, page_num, error_form=None):
    try:
        profile = UserProfile.objects.get(belong_to_id=page_num)
        if request.user.is_authenticated:
            id = request.user.id
            username = request.user.username
            if error_form is not None:
                form = error_form
            else:
                form = ProfileForm
    except:
        return redirect(to='index')
    page_int = int(page_num)
    return render(request, "basic/profile.html", locals())

templates/basic/PrivacyPolite.html
{% include 'basic/index_base.html' %}

{% block content %}
    <div class="ui segment container">
        <div class="ui grid">
            <div class="two wide column"></div>
            <div class="twelve wide column">
                <h1>Privacy Policy</h1>


                <p>Effective date: October 19, 2018</p>


                <p>djangowebsite ("us", "we", or "our") operates the http://djangowebsite.nctu.me/ website (hereinafter referred to as the "Service").</p>

                <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. Our Privacy Policy  for djangowebsite is managed with the help of <a href="https://privacypolicies.com/free-privacy-policy-generator/">Privacy Policies</a>.</p>

                <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from http://djangowebsite.nctu.me/</p>


                <h2>Information Collection And Use</h2>

                <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

                <h3>Types of Data Collected</h3>

                <h4>Personal Data</h4>

                <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>

                <ul>
                <li>Email address</li><li>First name and last name</li><li>Cookies and Usage Data</li>
                </ul>

                <h4>Usage Data</h4>

                <p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

                <h4>Tracking & Cookies Data</h4>
                <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
                <p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
                <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                <p>Examples of Cookies we use:</p>
                <ul>
                    <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
                    <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                    <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
                </ul>

                <h2>Use of Data</h2>

                <p>djangowebsite uses the collected data for various purposes:</p>
                <ul>
                    <li>To provide and maintain the Service</li>
                    <li>To notify you about changes to our Service</li>
                    <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                    <li>To provide customer care and support</li>
                    <li>To provide analysis or valuable information so that we can improve the Service</li>
                    <li>To monitor the usage of the Service</li>
                    <li>To detect, prevent and address technical issues</li>
                </ul>

                <h2>Transfer Of Data</h2>
                <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
                <p>If you are located outside Taiwan and choose to provide information to us, please note that we transfer the data, including Personal Data, to Taiwan and process it there.</p>
                <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                <p>djangowebsite will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

                <h2>Disclosure Of Data</h2>

                <h3>Legal Requirements</h3>
                <p>djangowebsite may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
                <ul>
                    <li>To comply with a legal obligation</li>
                    <li>To protect and defend the rights or property of djangowebsite</li>
                    <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>To protect the personal safety of users of the Service or the public</li>
                    <li>To protect against legal liability</li>
                </ul>

                <h2>Security Of Data</h2>
                <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

                <h2>Service Providers</h2>
                <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>
                <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>



                <h2>Links To Other Sites</h2>
                <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
                <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>


                <h2>Children's Privacy</h2>
                <p>Our Service does not address anyone under the age of 18 ("Children").</p>
                <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>


                <h2>Changes To This Privacy Policy</h2>
                <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
                <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>


                <h2>Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, please contact us:</p>
                <ul>
                    <li>By email: zerosky1943@gmail.com</li>
                </ul>
            </div>
            <div class="two wide column"></div>
        </div>
    </div>
{% endblock %}

templates/basic/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.0/dist/semantic.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.semanticui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.0/dist/semantic.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.1/vue.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue-resource/0.7.0/vue-resource.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/whale.png' %}" />
    {% block title %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</body>
</html>

templates/basic/index.html
{% include 'basic/index_base.html' %}
{% load staticfiles %}

{% block title %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Homepage</title>
    <meta name="description" content="Examples for creative website header animations using Canvas and JavaScript" />
    <meta name="keywords" content="header, canvas, animated, creative, inspiration, javascript" />
    <meta name="author" content="Codrops" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/AnimatedHeaderBackgrounds/normalize.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/AnimatedHeaderBackgrounds/demo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/AnimatedHeaderBackgrounds/component.css' %}" />
    <link href='http://fonts.googleapis.com/css?family=Raleway:200,400,800|Clicker+Script' rel='stylesheet' type='text/css'>
    <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
{% endblock %}

{% block content %}
    <div class="container demo-2">
        <div class="content">
            <div id="large-header" class="large-header">
                <canvas id="demo-canvas"></canvas>
                <h1 class="main-title">Hello World</h1>
                <div class="ui five wide column"></div>
            </div>
            </div>
        </div>
        <section class="related">
        </section>
        <!-- Thanks -->
        <p class="ref">
            Animate designed by <a href="https://tympanus.net/codrops/author/rachsmith/">rachsmith</a>.
            Image from <a href="http://unsplash.com/">Unsplash</a>.
            Ornament made with the <a href="http://pixelbuddha.net/freebie/sable-kit-free">Free Sable Kit</a> from Pixel Buddha.
        </p>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/AnimatedHeaderBackgrounds/rAF.js' %}"></script>
    <script src="{% static 'js/AnimatedHeaderBackgrounds/demo-2.js' %}"></script>
{% endblock %}

templates/basic/index_base.html
{% include 'basic/base.html' %}
{% load staticfiles %}

{% block title %}
{% endblock %}

{% block content %}
    <div class="ui container">
        <div class="ui fixed basic vertical inverted segment">
            <div class="ui borderless fixed inverted menu" id="toolbar">
                <a class="item" href="{% url 'basic:index' %}">
                    <i style="margin-right: 2px" class="rocket icon"></i>Home
                </a>
                <a class="item" href="{% url 'weather:index' %}">
                    <i style="margin-right: 2px" class="sun middle aligned icon"></i>天氣預報
                </a>
                <a class="item" href="{% url 'news:index' %}">
                    <i style="margin-right: 2px" class="clipboard outline alternate middle aligned icon"></i>新聞搜尋
                </a>
                <a class="item" href="{% url 'gallery:index' %}">
                    <i style="margin-right: 2px" class="camera alternate middle aligned icon"></i>照片集
                </a>
                <a class="item" href="{% url 'youtube:index' %}">
                    <i style="margin-right: 2px" class="youtube alternate middle aligned icon"></i>Youtube播放清單
                </a>
                <a class="item" href="{% url 'recommend:index' %}">
                    <i style="margin-right: 2px" class="youtube middle aligned icon"></i>推薦歌單
                </a>
                <div class="ui right borderless secondary menu">
                    {% if request.user.is_authenticated %}
                        <a class="item" style="margin-bottom: 0px" href="{% url 'basic:profile' request.user.id %}">
                            {% if request.user.profile.user_img %}
                                <img class="ui avatar image" src="{{ MEDIA_URL }}{{ request.user.profile.user_img }}">
                            {% else %}
                                <img class="ui avatar image" src="{% static '/images/user.png'%}" alt="">
                            {% endif %}
                            <span style="margin-left:10px">{{ request.user.username }}</span>
                        </a>
                        <a class="ui item" href="{% url 'basic:logout' %}">Logout</a>
                    {% else %}
                        <a class="ui disabled item" style="margin-bottom: 0px">
                            <div>Anonymous</div>
                        </a>
                        <a class="ui item" href="{% url 'basic:login' %}">
                            <div>SignUp/Login</div>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% block detail %}
    {% endblock %}
    {% block js %}
    {% endblock %}
{% endblock %}

templates/basic/profile.html
{% include 'basic/index_base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Profile</title>
{% endblock %}

{% block content %}
    <div class="ui divider"></div>

    <div class="ui grid">
        <div class="three wide column"></div>

        <div class="ten wide column">
            <table class="ui celled striped table">
                <thead>
                    <tr><th colspan="2">Personal Info</th></tr>
                </thead>
                <tbody>
                    <tr><td class="collapsing">Avatar</td><td><img class="ui small centered image" src="{{ MEDIA_URL }}{{ profile.user_img }}"></td></tr>
                    <tr><td class="collapsing">Username</td><td>{{ profile.belong_to.username }}</td></tr>
                    <tr><td class="collapsing">Nickname</td><td>{{ profile.nickname }}</td></tr>
                </tbody>
            </table>

            <div class="ui divider"></div>


        <div class="three wide column"></div>
    </div>


{% endblock %}

templates/basic/register.html
{% extends 'basic/base.html' %}
{% load staticfiles %}

{% block title %}
    {% if source == 'Login' %}
        <title>Login</title>
    {% else %}
        <title>Register</title>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="background image" style="height: 100%">
        <div class="holder">
            <div class="ui container vertical segment">
                <div class="ui grid">
                    <div class="ui six wide column">
                        <a href="{% url 'basic:index' %}">
                            <img class="ui fluid image" src="{% static '/images/login_logo.png' %}">
                        </a>
                    </div>
                    <div class="ui ten wide column">
                        <div class="ui basic segment">
                            <span class="ui huge left floated header">{{ source }}</span>
                            {% if source == 'Login' %}
                                <a class="ui right floated tiny black button" href="{% url 'basic:register' %}"><i class="undo icon"></i>Register</a>
                            {% else %}
                                <a class="ui right floated tiny black button" href="{% url 'basic:login' %}"><i class="undo icon"></i>Login</a>
                            {% endif %}
                        </div>
                        <div class="ui basic padded segment">
                            <form class="ui tiny error form" method="POST">
                                {% if form.errors %}
                                    <div class="ui error message">
                                        {{ form.errors }}
                                    </div>
                                    {% for field in form %}
                                        <div class="{{ field.errors|yesno:'error,' }} field">
                                            {{ field.label }}
                                            {{ field }}
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    {% for field in form %}
                                        <div class="field">
                                            {{ field.label }}
                                            {{ field }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                {% csrf_token %}
                                <button type="submit" class="ui blue button">Submit</button>
                            </form>
{#                            <a href="{% url "social:begin" "facebook" %}">facebook</a>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}